### ISSUE TITLE
Create a list of all the needed events and their corresponding scenes.

### ISSUE THREAD

**Issue by NephalemCry** [HallowedDust5/Space-Trail#10]
- [ ] Determine dynamic and static scenes, as in interaction.
- [ ] Create base classes for each scene

**Comment by HallowedDust5** [comment]
By no means do we have to use all of these, I'm just writing these down here. By static, I mean no interaction, it's simply something that's happening to the player and there's no action to be taken, and dynamic are ones that require player action in one way or another.

Static is **bolded**.
Dynamic is _italicized_.


## Calamities

- [ ] 1. _Low temperature_
- [ ] 2. _Low Oxygen_
- [ ] 3. _"Space Sickness"_
- [ ] 4. _Electrical Problem_
- [ ] 5. _Injury_
- [ ] 6. _Bad/low water_
- [ ] 7. **Low food supply**
- [ ] 8. _Misplaced supply? (I don't know what this one means)_
- [ ] 9. **Homesick**
- [ ] 10. _Engine Failure_
- [ ] 11. _Hole in ship, ties with low oxygen_

## Angelic Yields

- [ ] 1. **Found Supply/food**
- [ ] 2. **Salvage old satellite**
