### ISSUE TITLE
Low Temperature Event

### ISSUE THREAD

**Issue by HallowedDust5** [HallowedDust5/Space-Trail#13]
Follow this picture for the general layout of the scene. **_Make sure to NOT hardcode the units in pixels_**, code the dimensions of anything on screen in terms of the height or width of the screen, just in case we decide to make it bigger or smaller:
![image](https://user-images.githubusercontent.com/77157773/154170963-108d006f-b393-46a3-be96-56fe6e773d39.png)

To close the issue make sure these things are done
- [ ] Center all assets along the backing scene rectangle
- [x] Create snowflake asset
- [ ] Event scene does not overlap with the UI
- [ ] Buttons actually change the stats object when pressed

The picture doesn't have buttons. Have 2 buttons: one that takes away the low temp, but you lose a canister of water, and one that allows for the player to go to the next scene.

**Comment by NephalemCry** [comment]
Snowthumbnail.png encompasses the entire thumbnail for the pop-up. The size is set in pixels.
