### ISSUE TITLE
Broken Temperature Gauge Event

### ISSUE THREAD

**Issue by HallowedDust5** [HallowedDust5/Space-Trail#16]
Follow this picture for the general layout of the scene. **_Make sure to NOT hardcode the units in pixels_**, code the dimensions of anything on screen in terms of the height or width of the screen, just in case we decide to make it bigger or smaller:
![image](https://user-images.githubusercontent.com/77157773/154174743-406b7faa-c552-486a-9309-48b2e1fa6496.png)
69 nice

To close the issue make sure these things are done
- [ ] Center all assets along the backing scene rectangle
- [ ] Event scene does not overlap with the UI
- [ ] Buttons actually change the stats object when pressed

The picture doesn't have buttons. Have 2 buttons: one that takes away the broken temp gauge, but you lose 1 spare part, and one that allows for the player to go to the next scene, but the temp gauge remains broken..

**Comment by NephalemCry** [comment]
Is this too similar to the low temp event?

**Comment by HallowedDust5** [comment]
It's similar, but that's ok if we just have one or two things that are relatively similar imo
