### ISSUE TITLE
Low Oxygen Event

### ISSUE THREAD

**Issue by HallowedDust5** [HallowedDust5/Space-Trail#19]
Follow this picture for the general layout of the scene. **_Make sure to NOT hardcode the units in pixels_**, code the dimensions of anything on screen in terms of the height or width of the screen, just in case we decide to make it bigger or smaller:
![image](https://user-images.githubusercontent.com/77157773/154175616-abb91b10-7963-4f68-8239-58e19385259d.png)

To close the issue make sure these things are done
- [x] Center all assets along the backing scene rectangle
- [ ] Event scene does not overlap with the UI
- [x] Buttons actually change the stats object when pressed

The picture doesn't have buttons. Have 2 buttons: one that takes away the low oxygen but costs 1 oxygen and one that lets you proceed but kills an astronaut per turn for 2 turns.

**Comment by NephalemCry** [comment]
o2thumbnail.png is the thumbnail for this event
